server.port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123
    username: root
    url: jdbc:mysql://localhost:3306/x-fblog?serverTimeZone=Asia/Shanghai&characterEncoding=UTF-8
  servlet:
    multipart:
      enabled: true
      # 最大支持文件大小
      max-file-size: 10MB
      # 最大支持请求大小
      max-request-size: 10MB
